application: rfactorhotlapserver
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: ./static

- url: /favicon\.ico
  static_files: images/favicon.png
  upload: images/favicon.png

- url: /admin/.*
  script: admin_handler.app
  login: admin

- url: /charts/.*
  script: charts_handler.app

- url: /servers/.*
  script: serverHandler.app

- url: /imageBlobs/.*
  script: serverstatus.app

- url: /imageBlobg/.*
  script: serverstatus.app

- url: /r/.*
  script: engine.app

- url: .*
  script: rfactorHotlaps.app

libraries:
- name: django
  version: "1.3"
