application: rfactorhotlapserver
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: ./bootstrap
  
- url: /jQuery
  static_dir: ./jQuery
  
- url: /images
  static_dir: ./images
    
- url: /html
  static_dir: ./html
    
- url: /css
  static_dir: ./css
    
- url: /js
  static_dir: ./js
  
- url: /favicon\.ico
  static_files: images/favicon.png
  upload: images/favicon.png

- url: .*
  script: rfactorHotlaps.app

libraries:
- name: django
  version: "1.3"